/**:
  ros__parameters:
    # --- Mechanical Linkage Geometry ---
    
    # Link Lengths (m)
    l3: 3.93582620
    l5: 2.52445618
    l7: 1.14011468
    l8: 0.97728480
    l10: 0.45989269
    L_bkt: 1.60739
    H_bkt: 1.01077
    r: 1.69375

    # Angle Offsets (degrees)
    alpha1_deg: 29.701018799463878
    alpha2_deg: 50.58594847780444
    alpha3_deg: 16.79066
    alpha7_deg: 99.49

    # Rotation Joint Limits [min, max] (degrees)
    limit_beta1_deg: [-0.5, 100.0]
    limit_beta2_deg: [-0.5, 100.0]
    
    # --- System & Global Settings ---
    dt: 0.01
    y_offset: 2.1
    x_offset: 0.0

    # --- Trajectory Generator Settings ---
    vmax: [3.0, 1.5, 1.5] # [x, y, theta]
    amax: [1.0, 0.8, 0.8] # [x, y, theta]
    replan_period: 0.2
    arrival_tolerance: 0.1

    # --- State / Dig Cycle Settings ---
    bucket_width: 0.5
    target_volume: 2.0
    safety_factor: 1.5
    insert_length: 1.0
    max_insert_length: 2.5
    max_height: 4.0
    max_tilt_deg: 54.0

    # --- Visualization ---
    mode: "sim" # "real" or "sim"